### ISSUE TITLE
Fix/Off Agenda explanation

### ISSUE THREAD

**Issue by TerriWiseden** [SacCounty/request-to-speak#36]
SacCounty's current QA release of RTS contained an issue with how the SQL Server connection dealt with the InsertRequest stored procedure. The field "offAgenda" had been removed from the code in a previous merge with the develop branch.

To remedy this, the field needs to be added back to the code that calls InsertRequest and UpdateRequest stored procedures.

**Comment by gh0st** [comment]
This references #35.

**Comment by gh0st** [comment]
This was closed with #35.
